In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import statsmodels.formula.api as smf

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [16]:
hockey = pd.read_csv('/Users/Allison/desktop/Hockey/NHL_data.csv')

In [17]:
hockey.head()

,#,DOB,Birth City,S/P,Ctry,Nat,HT,Wt,S,Draft,...,3rd Star,Days,Ginj,Injury,Salary,Cap Hit,Cap Cost,CHIP,Bonuses,GVS
0,8.0,1987-02-25,Muskegon,MI,USA,USA,74,218,L,2005.0,...,4,186,0,NaN,2.250,1.800,1.800,0,0.0,1.6
1,55.0,1991-12-01,Johnston,RI,USA,USA,70,208,R,NaN,...,0,40,0,NaN,0.693,0.793,0.170,0,0.0,-1.0
2,51.0,1992-04-30,Morristown,NJ,USA,USA,72,202,L,2010.0,...,0,6,0,NaN,0.830,0.830,0.024,0,0.0,-0.3
3,28.0,1991-01-03,Kleinburg,ON,CAN,CAN,70,187,L,NaN,...,0,19,0,NaN,0.600,0.600,0.061,0,0.0,0.1
4,27.0,1988-09-24,Burnaby,BC,CAN,CAN,74,214,L,2007.0,...,1,186,0,NaN,2.800,2.800,2.800,0,0.0,3.8

In [7]:
#initial data exploration
hockey.describe()

,#,HT,Wt,Draft,Round,Overall,Age,Tm1GP,GP,G,...,2nd Star,3rd Star,Days,Ginj,Salary,Cap Hit,Cap Cost,CHIP,Bonuses,GVS
count,891.000000,898.000000,898.000000,766.000000,766.000000,766.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,896.000000,898.000000,898.000000,898.000000,898.000000,898.000000
mean,34.519641,73.150334,201.648107,2007.506527,2.830287,71.476501,26.283964,47.074610,49.307350,7.310690,...,1.120267,1.125835,147.054566,6.997773,2.225548,2.179072,2.084876,245.755011,0.110664,0.247439
std,23.865692,2.120849,14.956302,4.396889,2.048413,64.937708,4.431139,29.392474,29.402545,8.584573,...,1.785926,1.541973,81.544732,12.447258,2.174930,2.000460,2.128577,558.315213,0.435676,3.871328
min,2.000000,65.000000,157.000000,1990.000000,1.000000,1.000000,18.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-11.700000
25%,15.000000,72.000000,191.000000,2004.000000,1.000000,18.000000,23.000000,16.250000,20.000000,1.000000,...,0.000000,0.000000,83.000000,0.000000,0.700000,0.722000,0.346500,0.000000,0.000000,-1.400000
50%,28.000000,73.000000,201.000000,2008.000000,2.000000,51.000000,25.000000,55.000000,60.000000,4.000000,...,0.000000,0.000000,186.000000,1.000000,0.925000,0.925000,1.128000,22.000000,0.000000,0.000000
75%,51.000000,75.000000,211.000000,2011.000000,4.000000,111.750000,29.000000,75.000000,77.000000,11.000000,...,2.000000,2.000000,186.000000,10.000000,3.500000,3.500000,3.658000,220.000000,0.000000,1.700000
max,97.000000,81.000000,260.000000,2015.000000,9.000000,291.000000,43.000000,82.000000,84.000000,50.000000,...,14.000000,9.000000,552.000000,81.000000,14.000000,10.500000,10.500000,5433.000000,5.700000,14.700000

In [8]:
#checking for null values
hockey.isnull().sum().sort_values(ascending=False)

OpenFOW    711
OpenFOT    711
Rk         672
SOS        668
SOG        668
SOGDG      668
FOTvsR     420
Injury     411
FOTvsL     379
S/P        222
Draft      132
Round      132
Overall    132
#            7
HitA         5
Blocked      5
Salary       2
Nat          2
S            1
Ctry         0
IAP          0
IPP          0
FOW          0
FOL          0
FO%          0
Wt           0
HT           0
FOWvsL       0
Age          0
Pa/60        0
          ...
T/60         0
PS/60        0
Bonuses      0
Minor        0
Major        0
Misc         0
G Misc       0
Match        0
Grit         0
NetPen       0
SO%          0
1G           0
OTG          0
GWG          0
ENG          0
BHG          0
DeflG        0
SlapG        0
SnapG        0
TipG         0
WrapG        0
WristG       0
PSG          0
PST          0
PS%          0
OPS          0
DPS          0
PS           0
PS/G         0
PIM          0
dtype: int64

In [9]:
hockey.OpenFOW.describe()

count    187.000000
mean       6.572193
std        7.871883
min        0.000000
25%        1.000000
50%        3.000000
75%        9.000000
max       41.000000
Name: OpenFOW, dtype: float64

In [13]:
hockey.OpenFOW.fillna(value=0) 
hockey.OpenFOT.fillna(value=0)

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10     14.0
11      0.0
12      2.0
13      0.0
14      0.0
15      0.0
16      0.0
17     22.0
18     12.0
19     49.0
20      0.0
21      0.0
22      0.0
23      0.0
24     37.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
       ...
868     0.0
869     1.0
870     0.0
871     0.0
872     0.0
873     0.0
874     0.0
875     0.0
876     0.0
877     0.0
878     0.0
879     0.0
880     0.0
881     0.0
882     0.0
883     0.0
884     0.0
885     0.0
886     0.0
887     1.0
888     0.0
889    38.0
890     0.0
891    25.0
892    20.0
893     0.0
894     0.0
895     0.0
896     0.0
897     0.0
Name: OpenFOT, dtype: float64

In [14]:
hockey.isnull().sum().sort_values(ascending=False)

OpenFOW    711
OpenFOT    711
Rk         672
SOS        668
SOG        668
SOGDG      668
FOTvsR     420
Injury     411
FOTvsL     379
S/P        222
Draft      132
Round      132
Overall    132
#            7
HitA         5
Blocked      5
Salary       2
Nat          2
S            1
Ctry         0
IAP          0
IPP          0
FOW          0
FOL          0
FO%          0
Wt           0
HT           0
FOWvsL       0
Age          0
Pa/60        0
          ...
T/60         0
PS/60        0
Bonuses      0
Minor        0
Major        0
Misc         0
G Misc       0
Match        0
Grit         0
NetPen       0
SO%          0
1G           0
OTG          0
GWG          0
ENG          0
BHG          0
DeflG        0
SlapG        0
SnapG        0
TipG         0
WrapG        0
WristG       0
PSG          0
PST          0
PS%          0
OPS          0
DPS          0
PS           0
PS/G         0
PIM          0
dtype: int64

In [ ]:
hockey.plot(kind='scatter', x='Draft', y='G', c='Salary', xlim=(0, 25), ylim=(0, 250))